### ISSUE TITLE
Returing after Insert doesn't work

### ISSUE THREAD

**Issue by fl0wo** [notrab/libsql-middleware#10]
Hi, I'm using [Drizzle Insert with Returning](https://orm.drizzle.team/docs/insert#insert-returning) with an AfterInsert hook.

Everything works fine, but the just created row is not returned from the method (instead is returned an empty array)

Here's the afterExec implementation:
```
async afterExecute(result: ResultSet, query: InStatement, ___: Client) {
        if (!isInsertForTable(query, this.tableName)) {
            return result; // return result
        }

        const row = result?.rows?.pop() as T;
        if (!row) {
            throw new Error('Row is not set');
        }

        await this.execWithRow( // my stuff
            row
        );

        return result;  // return result
    }
```

Again everything works as expected, the only issue is related to the returning object. When using a turso client without hooks it works:

```
// TursoClient withLibsqlHooks (returning returns an empty array)
export function buildTursoClientEdgeWithHooks(context: TursoDbEnv,plugins:LibSQLPlugin[]) {
    const {url, authToken} = buildClient(context);
    const tursoClient = createClientEdge({url, authToken});
    const tursoClientWithHooks = withLibsqlHooks(tursoClient, plugins);
    return drizzle(tursoClientWithHooks, {schema});
}

// TursoClient without hooks, (returns the row/s inserted)
export function buildTursoClientEdge(context?: TursoDbEnv) {
    const {url, authToken} = buildClient(context);
    const tursoClient = createClientEdge({url, authToken});
    return drizzle(tursoClient, {schema});
}
```

Here's my insert query, but I think any similar insert would have the same behaviour:
```
         this.buildTursoClientEdgeWithHooks(ctx,this.plugins)
              .insert(schema.users)
              .values(InsertUserSchema.parse(args))
              .returning()) as Promise<Array<UserTurso>>, // instead received an empty array when using a client with hooks
```

**Comment by notrab** [comment]
Hey @fl0wo, I'll take a look at this.

Do you happen to have a repo with the basics in to replicate this?

**Comment by fl0wo** [comment]
Hi notrab, no rush.
I'll try to build a reproduction repo this weekend.

As current workaround I'm re-querying the data after the insert instead of using the response of the inserting query.

**Comment by notrab** [comment]
Hey @fl0wo 

I created a Drizzle example in the repo, perhaps you could create a repro from that? https://github.com/notrab/libsql-client-hooks/tree/main/examples/drizzle

**Comment by notrab** [comment]
@fl0wo here's what I see in side `afterExecute` when using `returning()`:

```bash
After executing: ResultSetImpl {
  columns: [ "id", "name" ],
  columnTypes: [ "INTEGER", "TEXT" ],
  rows: [
    {
      "0": 5,
      "1": "Test User",
      id: 5,
      name: "Test User",
    }
  ],
  rowsAffected: 0,
  lastInsertRowid: undefined,
  toJSON: [Function: toJSON],
}
```

The `row` which is identified like this:

```bash
{
      "0": 5,
      "1": "Test User",
      id: 5,
      name: "Test User",
    }
```

Is kinda expected? Since it's the client `.rows` that does the formatting, which hasn't been parsed yet.

Perhaps there's a way to hook into that inside `afterExecute` 🤔

**Comment by fl0wo** [comment]
Hi @notrab seems that inside the "afterExecute" there's no issues obtaining the returned object, exactly.

My concern is, the drizzle client "returning()" method, is not returning the object inserted no-more (when using hooks/handler).

I'm using libsql-handler 1.4.0.

I'll try to find the time to create a reproduction repo <3

**Comment by fl0wo** [comment]
OMG it's my bad...
<img width="531" alt="image" src="https://github.com/user-attachments/assets/7195aabd-e15f-4d3b-85b0-20934d79ba9c">


I'm doing .pop() from the row array, ofc the returning result is empty....

BAD AFTER HOOK:

```
async afterExecute(result: ResultSet, query: InStatement, ___: Client) {
        if (!isInsertForTable(query, this.tableName)) {
            return result;
        }

        const row = result?.rows?.pop() as T;
        
        if (!row) {
            throw new Error('Row after is not set');
        }

        const tableName = extractTableNameFromQuery(query);

        await this.execWithRow(
            tableName,
            row
        );

        return result;
    }

```
